global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker'
#    static_configs:
    #  - targets: ['host.docker.internal:9090', 'host.docker.internal:80', 'host.docker.internal:5173','host.docker.internal:3000']
  - job_name: 'prometheus'
    static_configs:
        - targets: ['localhost:30090']
  - job_name: 'api'
    static_configs:
        - targets: ['api:30080']
  - job_name: 'web'
    static_configs:
        - targets: ['web:30173']
  - job_name: 'node-exporter'
    static_configs:
        - targets: ['node-exporter:9100']
