apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: proyecto-avatares
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-configuracion
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configuracion
  namespace: proyecto-avatares
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'api'
        static_configs:
          - targets: ['api:80']
      - job_name: 'web'
        static_configs:
          - targets: ['web:5173']
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: proyecto-avatares
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30900
  selector:
    app: prometheus