version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
     - 80:80
    networks:
      - proyecto-avatares
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
        
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    networks:
      - proyecto-avatares
    depends_on:
      - api

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - proyecto-avatares

  grafana:
    #image: grafana/grafana:latest
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - proyecto-avatares
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage: {}


networks:
  proyecto-avatares:
    driver: bridge