version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
     - 80:80
    networks:
      - proyecto-avatares
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
        
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    networks:
      - proyecto-avatares
    depends_on:
      - api

networks:
  proyecto-avatares:
    driver: bridge