global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'avatares-monitor'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'api'
    static_configs:
      - targets: ['api:80']
    metrics_path: /metrics
  - job_name: 'web'
    static_configs:
      - targets: ['web:5173']
    metrics_path: /metrics
